rm -rf ./build
mkdir ./build

pushd ./build

cmake .. \
    -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
    -DMNN_LOW_MEMORY=true \
    -DMNN_CPU_WEIGHT_DEQUANT_GEMM=true \
    -DMNN_BUILD_LLM=true \
    -DMNN_SUPPORT_TRANSFORMER_FUSE=true \
    -DMNN_ARM82=false \
    -DMNN_USE_LOGCAT=true \
    -DMNN_OPENCL=true \
    -DLLM_SUPPORT_VISION=true \
    -DMNN_BUILD_OPENCV=true \
    -DMNN_IMGCODECS=true \
    -DLLM_SUPPORT_AUDIO=true \
    -DMNN_BUILD_AUDIO=true \
    -DMNN_BUILD_DIFFUSION=ON \
    -DMNN_SEP_BUILD=OFF \
    -DMNN_BUILD_CONVERTER=ON \
    -DMNN_AVX512=false \
    -DMNN_BUILD_TEST=true

make -j8
popd


# MNN_USE_SYSTEM_LIB
    # -DMNN_BUILD_CONVERTER=ON \
    # -DMNN_BUILD_TORCH=ON
    # -DMNN_FORBID_MULTI_THREAD=ON \
    # -DMNN_USE_THREAD_POOL=OFF
